version: 1.0.{build}
image: Visual Studio 2017
clone_folder: c:\mg
environment:
  MSYS2_DIR: msys64

  matrix:
    - MSYSTEM: MINGW64
      myarch: x86_64

artifacts:
  - path: mupen64plus-GLideN64-*.zip

build_script:
- del C:\Windows\System32\libssl-*.dll C:\Windows\system32\libcrypto-*.dll
- del C:\Windows\SysWOW64\libssl-*.dll C:\Windows\SysWOW64\libcrypto-*.dll
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%

    git submodule update --init

    @echo on

    SET "PATH=C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;%PATH%"

    bash -c "pacman -Syu --noconfirm"
    
    bash -c "pacman -Syu --force --noconfirm"

    bash -c "pacman -S --needed --noconfirm --disable-download-timeout mingw-w64-$myarch-nasm mingw-w64-$myarch-freetype mingw-w64-$myarch-libpng mingw-w64-$myarch-libsamplerate mingw-w64-$myarch-SDL2 mingw-w64-$myarch-jasper mingw-w64-$myarch-qt5 mingw-w64-$myarch-python3-pip mingw-w64-$myarch-python3-pyopenssl zip"

    cd %APPVEYOR_BUILD_FOLDER%

    bash -c "./build.sh"

test: off
